// Generated by ReScript, PLEASE EDIT WITH CARE

import Peerjs from "peerjs";

function makePeerNew(prim) {
  return new Peerjs(prim);
}

function makePeerWithIdNew(prim0, prim1) {
  return new Peerjs(prim0, prim1);
}

function connect(prim0, prim1) {
  return prim0.connect(prim1);
}

function send(prim0, prim1) {
  prim0.send(prim1);
}

function onOpen(prim0, prim1, prim2) {
  prim0.on(prim1, prim2);
}

function onConnection(prim0, prim1, prim2) {
  prim0.on(prim1, prim2);
}

function onData(prim0, prim1, prim2) {
  prim0.on(prim1, prim2);
}

function onClose(prim0, prim1, prim2) {
  prim0.on(prim1, prim2);
}

function onError(prim0, prim1, prim2) {
  prim0.on(prim1, prim2);
}

function onConnOpen(prim0, prim1, prim2) {
  prim0.on(prim1, prim2);
}

function onConnError(prim0, prim1, prim2) {
  prim0.on(prim1, prim2);
}

var PeerJs = {
  makePeerNew: makePeerNew,
  makePeerWithIdNew: makePeerWithIdNew,
  connect: connect,
  send: send,
  onOpen: onOpen,
  onConnection: onConnection,
  onData: onData,
  onClose: onClose,
  onError: onError,
  onConnOpen: onConnOpen,
  onConnError: onConnError
};

export {
  PeerJs ,
}
/* peerjs Not a pure module */
