// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function getViewportInfo() {
  var width = window.innerWidth;
  var height = window.innerHeight;
  var isMobile = width < 768;
  var isLandscape = width > height;
  var shouldRecommendLandscape = isMobile && !isLandscape && width < 640;
  return {
          width: width,
          height: height,
          isMobile: isMobile,
          isLandscape: isLandscape,
          shouldRecommendLandscape: shouldRecommendLandscape
        };
}

function useViewport() {
  var match = React.useState(function () {
        return getViewportInfo();
      });
  var setViewport = match[1];
  React.useEffect((function () {
          var handleResize = function () {
            setViewport(function (param) {
                  return getViewportInfo();
                });
          };
          window.addEventListener("resize", handleResize);
          window.addEventListener("orientationchange", handleResize);
          return (function () {
                    window.removeEventListener("resize", handleResize);
                    window.removeEventListener("orientationchange", handleResize);
                  });
        }), []);
  return match[0];
}

export {
  getViewportInfo ,
  useViewport ,
}
/* react Not a pure module */
