// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BoardSlot(props) {
  var card = props.card;
  return JsxRuntime.jsx("div", {
              children: card !== undefined ? card.toString() : "",
              className: "w-16 h-24 m-2 flex items-center justify-center border-2 border-dashed rounded-lg bg-gray-100"
            });
}

var make = BoardSlot;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
