// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BoardSlot(props) {
  var __teamColor = props.teamColor;
  var __className = props.className;
  var card = props.card;
  var className = __className !== undefined ? __className : "";
  var teamColor = __teamColor !== undefined ? __teamColor : "blue";
  var textColorClass = teamColor === "blue" ? "text-blue-600" : "text-red-600";
  return JsxRuntime.jsx("div", {
              children: card !== undefined ? JsxRuntime.jsx("span", {
                      children: card.toString(),
                      className: textColorClass + " text-2xl"
                    }) : null,
              className: "w-16 h-24 m-2 flex items-center justify-center border-2 border-dashed rounded-lg bg-gray-100 " + className
            });
}

var make = BoardSlot;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
