// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Card(props) {
  var __isHidden = props.isHidden;
  var __teamColor = props.teamColor;
  var __disabled = props.disabled;
  var __selected = props.selected;
  var onClick = props.onClick;
  var number = props.number;
  var selected = __selected !== undefined ? __selected : false;
  var disabled = __disabled !== undefined ? __disabled : false;
  var teamColor = __teamColor !== undefined ? __teamColor : "blue";
  var isHidden = __isHidden !== undefined ? __isHidden : false;
  var cardColor = function (n) {
    if (n === 0) {
      return "bg-gray-300";
    } else if (n % 2 === 1) {
      return "bg-white text-black border-gray-400";
    } else {
      return "bg-gray-800 text-white border-gray-700";
    }
  };
  var ringClass = selected ? (
      teamColor === "blue" ? " ring-4 ring-blue-400" : " ring-4 ring-red-400"
    ) : "";
  var classes = "rounded-lg border shadow flex items-center justify-center w-16 h-24 m-2 text-2xl transition-all " + cardColor(number) + ringClass + (
    disabled ? " opacity-40 cursor-not-allowed" : " cursor-pointer"
  );
  return JsxRuntime.jsx("div", {
              children: isHidden ? null : number.toString(),
              className: classes,
              onClick: (function (param) {
                  if (!disabled && onClick !== undefined) {
                    return onClick();
                  }
                  
                })
            });
}

var make = Card;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
