// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Card(props) {
  var __selected = props.selected;
  var onClick = props.onClick;
  var number = props.number;
  var selected = __selected !== undefined ? __selected : false;
  var cardColor = function (n) {
    if (n % 2 === 1) {
      return "bg-white text-black border-gray-400";
    } else {
      return "bg-gray-800 text-white border-gray-700";
    }
  };
  var classes = "rounded-lg border shadow flex items-center justify-center w-16 h-24 m-2 text-2xl cursor-pointer transition-all " + cardColor(number) + (
    selected ? " ring-4 ring-blue-400" : ""
  );
  return JsxRuntime.jsx("div", {
              children: number.toString(),
              className: classes,
              onClick: (function (param) {
                  if (onClick !== undefined) {
                    return onClick();
                  }
                  
                })
            });
}

var make = Card;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
