// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function LandscapeRecommendation(props) {
  var onDismiss = props.onDismiss;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            className: "w-12 h-1 bg-gray-300 rounded mx-auto mb-4"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    children: "↻",
                                    className: "text-4xl mb-4 text-blue-500 font-bold"
                                  }),
                              JsxRuntime.jsx("h3", {
                                    children: "가로 모드 권장",
                                    className: "text-lg font-bold mb-2 text-gray-800"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "더 나은 게임 경험을 위해 기기를 가로로 회전해주세요.",
                                    className: "text-gray-600 mb-6 text-sm leading-relaxed"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("button", {
                                            children: "확인",
                                            className: "bg-blue-500 text-white px-6 py-3 rounded-lg font-medium hover:bg-blue-600 transition-colors w-full",
                                            onClick: (function (param) {
                                                onDismiss();
                                              })
                                          }),
                                      JsxRuntime.jsx("p", {
                                            children: "가로 모드로 변경하면 이 메시지가 자동으로 사라집니다.",
                                            className: "text-xs text-gray-500"
                                          })
                                    ],
                                    className: "flex flex-col space-y-3"
                                  })
                            ],
                            className: "text-center"
                          })
                    ],
                    className: "bg-white rounded-t-2xl p-6 w-full max-w-md mx-4 mb-0 shadow-2xl animate-slide-up"
                  }),
              className: "fixed inset-0 bg-black bg-opacity-50 flex items-end justify-center z-50"
            });
}

var make = LandscapeRecommendation;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
