// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function MobileGameTabs(props) {
  var onTabChange = props.onTabChange;
  var activeTab = props.activeTab;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "내 패",
                              className: activeTab === "MyView" ? "flex-1 py-3 px-4 text-center font-semibold text-blue-600 border-b-2 border-blue-600 bg-blue-50" : "flex-1 py-3 px-4 text-center font-medium text-gray-600 border-b-2 border-transparent hover:text-gray-800",
                              onClick: (function (param) {
                                  onTabChange("MyView");
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "상대 패",
                              className: activeTab === "OpponentView" ? "flex-1 py-3 px-4 text-center font-semibold text-blue-600 border-b-2 border-blue-600 bg-blue-50" : "flex-1 py-3 px-4 text-center font-medium text-gray-600 border-b-2 border-transparent hover:text-gray-800",
                              onClick: (function (param) {
                                  onTabChange("OpponentView");
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "게임 보드",
                              className: activeTab === "GameBoard" ? "flex-1 py-3 px-4 text-center font-semibold text-blue-600 border-b-2 border-blue-600 bg-blue-50" : "flex-1 py-3 px-4 text-center font-medium text-gray-600 border-b-2 border-transparent hover:text-gray-800",
                              onClick: (function (param) {
                                  onTabChange("GameBoard");
                                })
                            })
                      ],
                      className: "flex"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "Score: " + String(props.myWins) + " - " + String(props.oppWins),
                                      className: "font-medium"
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: "Round " + String(props.currentRound + 1 | 0) + "/9",
                                      className: "text-gray-600"
                                    })
                              ],
                              className: "flex justify-between items-center"
                            }),
                        props.waiting ? JsxRuntime.jsx("div", {
                                children: "상대방을 기다리는 중...",
                                className: "text-center text-blue-600 mt-1"
                              }) : null
                      ],
                      className: "px-4 py-2 bg-gray-50 text-sm"
                    })
              ],
              className: "bg-white border-b border-gray-200"
            });
}

var make = MobileGameTabs;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
